### ISSUE TITLE
DeviceActor::Stop not exiting cleanly

### ISSUE THREAD

**Issue by timlaverty** [Azure/device-simulation-dotnet#56] opened 2017-09-18 22:29 UTC
# Type of issue

- [x ] Bug
- [ ] New feature
- [ ] Improvement

# Description
This tracks a todo in the stop function for DeviceActor.  The function doesn't exit cleanly... this happens only when the actor is being shut down - the thread dies so it's not critical but we should still cleanup & fix it.  Feels dirty.

            //TODO: I see this not exiting cleanly sometimes in the logs (it throws)

**Comment by dluc** [comment] 2017-10-17 01:56
Fixed in https://github.com/Azure/device-simulation-dotnet/pull/95.
Briefly, the root cause were/are multiple concurrent requests to stop the simulation, coming through the actor stop and the cancellation token. The requests are fine, because the solution is trying to stop asap, so the solution is to handle the concurrent disposition of resources.
A better way of handling add/remove devices will also limit this scenario only to the user asking to stop the simulation, while now this happens more often when adding/removing simulated devices too.

**Closed by dluc** 2017-10-17 01:56 UTC
Labels: GA, P1, Triaged
