### ISSUE TITLE
RatedCounter.cs Throws System.NullReferenceException When Running WebService in VS2017

### ISSUE THREAD

**Issue by scout208** [Azure/device-simulation-dotnet#122] opened 2017-11-09 21:59 UTC
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
The first time that the program tries to run a line containing a reference to `Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Concurrency.PerSecondCounter.log` it throws a `System.NullReferenceException` because the log property hasn't been assigned a value yet.
...

# Steps to reproduce 

1.  Run the Storage Adapter microservice. 
2. Open the device-simulation solution in VS2017.
3.  Edit the WebService and SimulationAgent project properties, and define the required environment variables, or set these in your system on Windows.
4. In Visual Studio, start the WebService project.

# Expected behavior 
The program should run without throwing any terminating exceptions.

# Current behavior 
The program terminates upon reaching the first line of log code in the RatedCounter class due to a NullReferenceException.

![image](https://user-images.githubusercontent.com/9426329/32631549-335d16d0-c566-11e7-98ed-4d7d19bad3ae.png)

# Known workarounds 
Moving `this.log = logger` above the code that throws the error allows the program to continue past the line the exception was thrown on before.

# Possible solution 
`this.log = logger` should be called at the top of the constructor to prevent this error from appearing.

![image](https://user-images.githubusercontent.com/9426329/32631727-b38e03aa-c566-11e7-87fd-768c33817c00.png)

# Context and Environment
* Operating System: Windows 10 Pro
* GitHub branch: master
* .NET Runtime: Don't know where to find this...

**Comment by dluc** [comment] 2017-11-16 01:18
@scout208 thank you for the thorough report, that really helped identifying the root cause 👍  A PR to address the issue is out for review, so the fix will be in the master branch soon.  Thanks!

**Closed** 2017-11-17 02:03 UTC
Labels: bug

**Comment by dluc** [comment] 2017-11-17 02:06
bug fixed in master, "testing" Docker image updated
